image: "python:3.7"

before_script:
    - python --version
    - pip install -r requirements.txt

stages:
    - Static Analysis
    - Test

mypy:
    stage: Static Analysis
    tags:
        - qsimulations
    allow_failure: true
    script:
    - pwd
    - ls -l
    - python -m mypy qTools/QuantumToolbox/*.py

flake8:
    stage: Static Analysis
    tags:
        - qsimulations
    allow_failure: true
    script:
    - flake8 --max-line-length=140 qTools/*.py

pylint:
    stage: Static Analysis
    tags:
        - qsimulations
    allow_failure: true
    script:
        - pylint --rcfile=.pylintrc --output-format=text qTools/*.py | tee pylint.txt || pylint-exit $?
        - score=$(sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' pylint.txt)
        - echo "Pylint score was $score"
        - anybadge --value=$score --file=public/pylint.svg pylint
    artifacts:
        paths:
            - public/pylint.svg
    only:
    - master

unit_test:
    stage: Test

    artifacts:
        paths:
        - public
    only:
    - master

    tags:
        - qsimulations
    allow_failure: true
    script:
    - pwd
    - ls -l
    - export PYTHONPATH="$PYTHONPATH:."
    - python -c "import sys;print(sys.path)"
    - pytest