before_script:
    - python3 --version

stages:
    - Static Analysis
    - Test

mypy:
    stage: Static Analysis
    tags:
        - qsimulations
    allow_failure: true
    script:
    - pwd
    - ls -l
    - cd qTools
    - python3 -m mypy QuantumToolbox

flake8:
    stage: Static Analysis
    tags:
        - qsimulations
    allow_failure: true
    script:
    - pwd
    - python3 -m flake8 --max-line-length=140 qTools/*.py

pylint:
    stage: Static Analysis
    tags:
        - qsimulations
    allow_failure: true
    script:
        - pwd
        - python3 -m pylint --rcfile=.pylintrc --output-format=text qTools/*.py | tee pylint.txt || pylint-exit $?
        - score=$(sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' pylint.txt)
        - echo "Pylint score was $score"
        - python3 -m anybadge --value=$score --file=pylint.svg pylint
    artifacts:
        paths:
            - pylint.svg
        when: always
        expire_in: 4 weeks

unit_test:
    stage: Test
    tags:
        - qsimulations
    allow_failure: true
    script:
    - pwd
    - ls -l
    - cd tests
    - python3 -m pytest
