stages:
    - demo
    - lint

demo:
    stage: demo
    tags:
        - qsimulations
    script:
        - echo qSims

pylint:
    image: "python:latest"
    stage: linttags:
        - qsimulations
    script:
        - pip install pylint
        - pylint src/